const CATEGORIES = {
  ANTI_IMMIGRATION: 'anti-immigration',
  ANTI_SCIENCE: 'anti-science',
  AWFUL_NOMINATIONS: 'awful-nominations',
  CORRUPTION: 'corruption',
  CRYPTO: 'crypto',
  FASCISM: 'fascism',
  FOREVER_GRIFTING: 'forever-grifting',
  FULL_STUPID: 'full-stupid',
  HEALTHCARE: 'healthcare',
  IMPERIALISM: 'imperialism',
  KILLING_DEMOCRACY: 'killing-democracy',
  LAWLESSNESS: 'lawlessness',
  LEOPARDS_ATE_MY_FACE: 'leopards-ate-my-face',
  LOSSES: 'losses',
  MONEY: 'money',
  NATIONAL_SECURITY: 'national-security',
  NAZI: 'nazi',
  NOT_AWFUL: 'not-awful',
  PERVERTS: 'perverts',
  PRO_LIFE: 'pro-life',
  RACISM: 'racism',
  RETRIBUTION: 'retribution',
  TRADE_WAR: 'trade-war',
  UNCONSTITUTIONAL: 'unconstitutional',
  TRUMPS_AMERICA: 'trumps-america',
  OLIGARCHY: 'oligarchy',
};

export default CATEGORIES;
